# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master  # Triggers on changes to the master branch

pool:
  name: Default  # This is your self-hosted agent pool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore ClassLibraryProjects.sln
  displayName: 'Restore Dependencies'

- script: dotnet build StringLibrary/StringLibrary.csproj --configuration Release
  displayName: 'Build Class Library'

- script: dotnet pack StringLibrary/StringLibrary.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'ClassLibraryProjects/MyNugetFeed'
    allowPackageConflicts: true
